feign:
  hystrix:
    enabled: false

eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://spring-cloud-workshop-service-discovery:8761/eureka/